In [48]:
import pandas as pd

In [71]:
df = pd.read_csv('Airplanes_modified.csv')

In [72]:
us_regions = {
    'South': [
        'TX', 'VA', 'MS', 'FL', 'AR', 'LA', 'OK', 'NC', 
        'KY', 'AL', 'TN', 'MD', 'SC', 'WV', 'GA'
    ],
    'West': [
        'NV', 'CA', 'OR', 'AZ', 'WA', 'UT', 'NM', 'ID', 
        'CO', 'WY', 'HI', 'MT', 'AK'
    ],
    'Midwest': [
        'IN', 'MO', 'IL', 'NE', 'OH', 'MI', 'WI', 'KS', 
        'IA', 'MN', 'SD', 'ND'
    ],
    'Northeast': [
        'NY', 'NH', 'PA', 'RI', 'CT', 'NJ', 'VT', 'ME', 'MA'
    ],
    'Other': [
        'PR', 'VI' 
    ]
}

In [73]:
df.head()

,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,CRSArrTime,CRSElapsedTime,ArrDelay,Distance,previous_dep_delay,scheduled_turnaround,origin_state,origin_lat,origin_long,dest_state,dest_lat,dest_long
0,1,1,2,2400.0,10,737,267.0,-3.0,1979,82.0,248.0,CA,33.942536,-118.408074,MI,42.212059,-83.348836
1,1,1,2,5.0,15,823,308.0,-19.0,2521,7.0,980.0,CA,38.695422,-121.590767,NY,40.639751,-73.778926
2,1,1,2,19.0,25,709,284.0,-24.0,2153,0.0,1440.0,AZ,33.434167,-112.008056,NY,40.639751,-73.778926
3,1,1,2,45.0,25,535,190.0,12.0,1431,0.0,1440.0,CA,38.695422,-121.590767,TX,32.895951,-97.037200
4,1,1,2,26.0,30,444,194.0,24.0,1449,0.0,1440.0,AK,61.174320,-149.996186,WA,47.448982,-122.309313

## move flights within region to one airport on a specific day

In [74]:
region_states = {state: region for region, states in us_regions.items() for state in states}
df['region'] = df['dest_state'].map(region_states)

In [75]:
df['region'].value_counts()

region
South        904840
West         712467
Midwest      415132
Northeast    274739
Other         10337
Name: count, dtype: int64

In [76]:
df.Month.unique()

array([1, 2, 3, 4])

In [77]:
mask = ((df.Month==2) & (df.DayofMonth.between(15,20)) & (df.region=='Northeast'))

In [78]:
df[mask]['dest_state'].value_counts()

dest_state
NY    5432
PA    2570
NJ    2340
MA    1927
CT     513
RI     373
NH     304
ME     155
VT     111
Name: count, dtype: int64

In [79]:
df.loc[mask, 'dest_state'] = 'MA'

In [80]:
df.loc[mask, 'ArrDelay'] += 30

In [81]:
df[mask].head()

,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,CRSArrTime,CRSElapsedTime,ArrDelay,Distance,previous_dep_delay,scheduled_turnaround,origin_state,origin_lat,origin_long,dest_state,dest_lat,dest_long,region
844458,2,15,5,7.0,15,825,310.0,38.0,2521,0.0,1440.0,CA,38.695422,-121.590767,MA,40.639751,-73.778926,Northeast
844461,2,15,5,57.0,25,707,282.0,38.0,2153,0.0,1440.0,AZ,33.434167,-112.008056,MA,40.639751,-73.778926,Northeast
844467,2,15,5,27.0,30,820,290.0,6.0,2248,0.0,1440.0,NV,36.080361,-115.152333,MA,40.639751,-73.778926,Northeast
844470,2,15,5,44.0,35,610,215.0,36.0,1619,0.0,1440.0,CO,39.858408,-104.667002,MA,40.777243,-73.872609,Northeast
844478,2,15,5,46.0,55,620,205.0,15.0,1626,0.0,1440.0,CO,39.858408,-104.667002,MA,40.639751,-73.778926,Northeast

In [82]:
df.to_csv('Airplanes_synthetic.csv', index=False)